// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig , env} from "prisma/config";
import dotenv from "dotenv";

dotenv.config();
//const DATABASE_URL = process.env.DATABASE_URL || env("DATABASE_URL");


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://postgres:password@localhost:5432/app_hours",
  },
});

        